/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace jclms {

public class HidProtocol {
  public static int Open(int lTimeOut) {
    int ret = HidProtocolPINVOKE.Open(lTimeOut);
    return ret;
  }

  public static int Close() {
    int ret = HidProtocolPINVOKE.Close();
    return ret;
  }

  public static int Notify(string pszMsg) {
    int ret = HidProtocolPINVOKE.Notify(pszMsg);
    return ret;
  }

  public static int SetRecvMsgRotine(SWIGTYPE_p_f_p_q_const__char__void pRecvMsgFun) {
    int ret = HidProtocolPINVOKE.SetRecvMsgRotine(SWIGTYPE_p_f_p_q_const__char__void.getCPtr(pRecvMsgFun));
    return ret;
  }

  public static void zwPushString(string str) {
    HidProtocolPINVOKE.zwPushString(str);
  }

  public static string dbgGetLockReturnXML() {
    string ret = HidProtocolPINVOKE.dbgGetLockReturnXML();
    return ret;
  }

  public static int OpenJson(int lTimeOut) {
    int ret = HidProtocolPINVOKE.OpenJson(lTimeOut);
    return ret;
  }

  public static int SendToLockJson(string pszJson) {
    int ret = HidProtocolPINVOKE.SendToLockJson(pszJson);
    return ret;
  }

  public static string RecvFromLockJson(int timeoutMs) {
    string ret = HidProtocolPINVOKE.RecvFromLockJson(timeoutMs);
    return ret;
  }

  public static int CloseJson() {
    int ret = HidProtocolPINVOKE.CloseJson();
    return ret;
  }

}

}
