/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace jclms {

public class ccbElock {
  public static int SecboxOpen() {
    int ret = ccbElockPINVOKE.SecboxOpen();
    return ret;
  }

  public static void SecboxClose(int handleHid) {
    ccbElockPINVOKE.SecboxClose(handleHid);
  }

  public static void SecboxSendAuthReq(int handleHid) {
    ccbElockPINVOKE.SecboxSendAuthReq(handleHid);
  }

  public static int SecboxVerifyAuthRsp(int handleHid) {
    int ret = ccbElockPINVOKE.SecboxVerifyAuthRsp(handleHid);
    return ret;
  }

  public static void SecboxWriteData(int handleHid, int index, string dataB64) {
    ccbElockPINVOKE.SecboxWriteData(handleHid, index, dataB64);
  }

  public static string SecboxReadData(int handleHid, int index) {
    string ret = ccbElockPINVOKE.SecboxReadData(handleHid, index);
    return ret;
  }

}

}
